  version: '3'
    
  services:
    web:
      container_name: pms_api_standalone
      image: rajankarki327/pms_api_v1
      command: bash -c "python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/django_docker
      ports:
        - "8007:8000"
  networks:
    default:
      external:
        name: postgres_db 
